repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
        exclude_types: [json]
      - id: mixed-line-ending
        types: [python]
      - id: trailing-whitespace
        types_or: [markdown, json, python, yaml]
      - id: check-yaml
      - id: check-json
