repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: end-of-file-fixer
    exclude_types: [svg]
  - id: mixed-line-ending
    types: [python]
  - id: trailing-whitespace
    types_or: [markdown, json, python, yaml]
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args: [--autofix]
  - id: file-contents-sorter
    files: ^fuji_server\/data\/.*.txt$
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-toml
    args: [--autofix, --indent, '2']
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.5.4
  hooks:
  - id: insert-license
    types: [python]
    args: [--license-filepath=docs/license_header.txt]
    exclude: docs
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.11
  hooks:
  - id: ruff
    args: [--fix, --show-fixes, --exit-non-zero-on-fix]
  - id: ruff-format
