[SERVICE]
service_host = "localhost"
service_port = 1071
yaml_directory = "yaml"
metrics_yaml = "metrics_v0.5.yaml"
openapi_yaml = "openapi.yaml"
debug_mode = true # set debug_mode to true to avoid online downloads of external files (during development)
data_files_limit = 5
log_config = "config/logging.ini"
logdir = "logs"
remote_log_host = "fuji.localhost" # the URI which triggers the remote logging all other F-UJI server requests are ignored
remote_log_path = "/loghandler/index.php"
rate_limit = "100 per minute"
max_content_size = 5000000 # limits the maximum size of content (metadata) which can be downloaded
google_custom_search_id = ""
google_custom_search_api_key = ""

[EXTERNAL]
lov_api = "https://lov.linkeddata.es/dataset/lov/api/v2/vocabulary/list"
lod_cloudnet = "https://lod-cloud.net/lod-data.json"
# bioportal_rest = http://data.bioontology.org
# bioportal_apikey =
