name: CI

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1 # colored output by pytest etc.

permissions:
  contents: read

jobs:

  docs:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Cache python dependencies
      id: cache-pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-docs-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          pip-docs-

    - name: Install python dependencies
      run: |
        pip install .[docs]
        pip show fuji

    - name: Build documentation
      env:
        READTHEDOCS: 'True'
      run: |
        # TODO: add W flag back after fixing warnings
        SPHINXOPTS='-n' make -C docs html

  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Cache python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pre-commit
        key: pip-pre-commit-${{ hashFiles('.pre-commit-config.yaml', 'pyproject.toml') }}
        restore-keys: |
          pip-pre-commit-
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - run: pip install pre-commit
    - name: Run pre-commit
      run: pre-commit run --all-files --color=always

  tests:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        python-version: ['3.9', '3.8']

    steps:
    - uses: actions/checkout@v3

    - name: Cache python dependencies
      id: cache-pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          pip-${{ matrix.python-version }}-tests

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        pip install .[testing]
        pip freeze
        pip show fuji

    - name: Run pytest
      run: pytest --cov
