name: Publish Docker image

on:
  workflow_dispatch:
  push:
    # Publish `master` as Docker `latest` image.
    branches: [master]
  release:
    types: [created]

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/fuji

jobs:

  # Refs:
  # https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages

  build-and-publish:
    # Build and push image to GitHub Container Registry https://docs.docker.com/docker-hub/builds/
    runs-on: ubuntu-22.04

    # do not run in forks
    # if: github.repository == 'pangaea-data-publisher/fuji'

    steps:

    - name: Set up docker buildx
      uses: docker/setup-buildx-action@v1

    - uses: actions/checkout@v4

    - name: Log in to GitHub container registry (ghcr.io)
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=tag
          type=semver,pattern={{version}}
          type=sha

    - name: Build and push docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
